### PR TITLE
Rename Baseline -> Indicators, Follow Up -> Observations

### PR DESCRIPTION
**Pull request by rebecca-caktus**
On the front end only.

### CODE REVIEW

**Comment by emullaney** [comment]
I think it's a little confusing that the second question is called "Follow Up" in some instances, "Observations" in others. 

"Follow Up" language on the list page and the update page.
"Observations" elsewhere.

**Comment by rebecca-caktus** [comment]
Good catch! Fixed now.

**Comment by emullaney** [comment]
Looks great. The data spoofing form still uses "follow up" terminology as well. Should we update that, so that it's the same everywhere?

**Comment by rebecca-caktus** [comment]
Updated again.

**Comment by emullaney** [comment]
:green_apple:

**Pull request merged**
