### PR TITLE
HT-15 Breakout Deployment

### PR DESCRIPTION
**Pull request by mlavin**
Removing deployment related pieces from this repo which will be managed separately going forward. Remaining work to update/move docs as well.

### CODE REVIEW

**Comment by emullaney** [comment]
There are references to the "conf" folder in https://github.com/rapidpro/tracpro/blob/develop/Makefile, should those be updated or moved to hosted-tracpro?

**Comment by mlavin** [comment]
Yes those should be removed here and moved as well. Good catch.

**Comment by mlavin** [comment]
Updated.

**Comment by emullaney** [comment]
:recycle:

**Pull request merged**
