### PR TITLE
Sort categories by numeric values or strings

### PR DESCRIPTION
**Pull request by emullaney**
Poll Detail - all multiple choice questions
Pollrun Detail - all results that aren't open-ended

### CODE REVIEW

**Comment by daaray** [comment]
Validated that categories are now sorted:

sorted_categories

Is it possible to add a quick test for this change as well?

**Comment by rebecca-caktus** [comment]
Great result!

`sort_by_category` is used after `category_counts_by_pollrun`, so maybe the category sorting could be completed in that function?

**Comment by rebecca-caktus** [comment]
You might also find the `key` argument to `sort()` relevant here:

```
def natural_category_key(category):
    # return what should actually be sorted on

list_of_things.sort(key=natural_category_key)
list_of_tuples.sort(key=lambda (a, b): natural_category_key(a))
```

**Comment by emullaney** [comment]
I've added a test per @daaray's suggestion.

@rebecca-caktus's  refactoring suggestions are excellent, however, I'd like to push this up now, and look at those suggestions at a later date, so we can get this fix out.

**Comment by daaray** [comment]
:fireworks: :fireworks: :fireworks:

**Pull request merged**
